config/routes.rb
Rails.application.routes.draw do
  resources :books
  root to: 'welcome#index'
  get 'welcome/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Almost every application defines a route for the root path ("/") at the top of this file.
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
  belongs_to :publisher
  belongs_to :genre

  include PgSearch::Model
  pg_search_scope :pg_search,
    against: :title,
    using: {
      tsearch: { dictionary: 'english' }
    },
    associated_against: {
      author: :name,
      publisher: :name,
      genre: :name
    }

  def self.search(query)
    return all unless query.present?

    # where(title: query)

    # where("title ILIKE ?", "%#{query}%")

    # where("to_tsvector('english', title) @@ plainto_tsquery('english', :q)", q: query)

    # where("to_tsvector('english', title) @@ plainto_tsquery('english', :q)", q: query)
    # .joins(:author).or(Book.where("authors.name ILIKE ?", "%#{query}%"))
    # .joins(:publisher).or(Book.where("publishers.name ILIKE ?", "%#{query}%"))
    # .joins(:genre).or(Book.where("genres.name ILIKE ?", "%#{query}%"))

    pg_search(query)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]

  # GET /books
  def index
    @books = Book.search(params[:q])
      .includes(:author, :publisher, :genre)
      .page(params[:page])
      .without_count
      .per(8)
  end

  # GET /books/1
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to @book, notice: "Book was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /books/1
  def update
    if @book.update(book_params)
      redirect_to @book, notice: "Book was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /books/1
  def destroy
    @book.destroy
    redirect_to books_url, notice: "Book was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :author_id, :publisher_id, :genre_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def query_array
    params[:q].to_s.split(' ')
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>" class="scaffold_record">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author_id %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.publisher_id %>
  </p>

  <p>
    <strong>Genre:</strong>
    <%= book.genre_id %>
  </p>

</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <div class="mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :author_id, class: 'form-label' %>
    <%= form.text_field :author_id, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :publisher_id, class: 'form-label' %>
    <%= form.text_field :publisher_id, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :genre_id, class: 'form-label' %>
    <%= form.text_field :genre_id, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<h1>Book</h1>

<%= form_with url: books_path, method: :get do |form| %>
  <div class='input-group'>
    <%= form.text_field :q, value: params[:q], placeholder: 'Search', class: 'form-control' %>
    <%= form.submit 'Search', class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

<table class='table'>
  <thead>
    <th>Title</th>
    <th>Author</th>
    <th>Publisher</th>
    <th>Genre</th>

    <th colspan=3>Actions</th>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= highlight(book.title, query_array) %></td>
        <td><%= highlight(book.author.name, query_array) %></td>
        <td><%= highlight(book.publisher.name, query_array) %></td>
        <td><%= highlight(book.genre.name, query_array) %></td>

        <td><%= link_to "Show", book_path(book) %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td><%= link_to "Delete", book_path(book), "data-turbo-method": :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%# paginate @books %>
<%= link_to_prev_page @books, 'Previous Page', class: 'btn btn-outline-primary' %>
<%= link_to_next_page @books, 'Next Page', class: 'btn btn-outline-primary' %>
<br>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<%= render @book %>

<div>
  <%= link_to "Edit", edit_book_path(@book) %> |
  <%= link_to "Destroy", book_path(@book), "data-turbo-method": :delete %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light py-4">
  <div class="container-fluid">
    <a class="navbar-brand" href="#" data-config-id="brand">
      <%= image_tag 'logo.png', class: 'img-fluid' %>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="nav">
      <ul class="d-none d-lg-flex navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <ul class="navbar-nav mt-3 mt-lg-0 mb-3 mb-lg-0 d-lg-none">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li class="nav-item me-4">
  <%= link_to "Home", root_path, class: 'nav-link' %>
</li>
<li class="nav-item me-4">
  <%= link_to "Books", books_path, class: 'nav-link' %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drifting Ruby</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class='bg-light'>
    <div class="container bg-white border pb-3">
      <%= render 'layouts/navigation' %>
      <% flash.each do |type, msg| %>
        <% if type == 'alert' %>
          <%= content_tag :div, msg, class: "alert alert-danger", role: :alert %>
          <% else %>
          <%= content_tag :div, msg, class: "alert alert-primary", role: :alert %>
        <% end %>
      <% end %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>